repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args: ['--allow-multiple-documents']
        exclude: 'charts/.*/templates/.*\.yaml$'
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
        exclude: '(charts/.*/README\.md$|charts/.*/ci/.*\.yaml$)'
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: detect-secrets
        name: Detect secrets
        language: python
        entry: detect-secrets-hook
        args: ['--baseline', '.secrets.baseline']
      - id: helm-lint-gateway
        name: Helm Lint Gateway Chart
        entry: bash -c 'helm lint charts/gateway'
        language: system
        pass_filenames: false
        files: ^charts/
      - id: helm-lint-console
        name: Helm Lint Console Chart
        entry: bash -c 'helm lint charts/console --set config.organization.name=test,config.admin.email=test@test.io,config.admin.password=test,config.database.password=test,config.database.username=test,config.database.host=test' # pragma: allowlist secret
        language: system
        pass_filenames: false
        files: ^charts/
      - id: helm-lint-provisioner
        name: Helm Lint Provisioner Chart
        entry: bash -c 'helm lint charts/provisioner'
        language: system
        pass_filenames: false
        files: ^charts/
      - id: readme-generator
        name: Generate Chart READMEs
        entry: make generate-readme
        language: system
        pass_filenames: false
        files: ^charts/.*/(values\.yaml|values\.schema\.json|README\.md)$
