apiVersion: v2
name: console
appVersion: 1.42.0
version: 1.26.1
description: Helm chart to deploy Conduktor Console on Kubernetes
icon: https://www.conduktor.io/svgs/logo/symbol.svg
home: https://www.conduktor.io
maintainers:
  - name: Conduktor
    email: support@conduktor.io
    url: https://docs.conduktor.io/platform
sources:
  - https://github.com/conduktor/conduktor-public-charts/tree/main/charts/console
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.30.2 # force version to avoid breaking changes due to remove support for older k8s versions in common chart v2.31.0 and above
