nameOverride: gateway-test-02

gateway:
  replicas: 1
  admin:
    port: 8888

  env:
    KAFKA_BOOTSTRAP_SERVERS: kafka.ct-gateway-deps.svc.cluster.local:9092
    GATEWAY_CLUSTER_ID: "gw-02"

service:
  external:
    enable: true
    type: LoadBalancer
    admin: true
    extraSpecs:
      externalTrafficPolicy: Local

  internal:
    extraSpecs:
      trafficDistribution: PreferClose

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: gateway.private
  tls: true
  selfSigned: true
