{{- if .Values.console.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "provisioner.console.config.secrets" . | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: conduktor-provisioning
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.console.password }}
  CDK_PASSWORD: {{ .Values.console.password | b64enc }}
  {{- end }}
  {{- if .Values.console.apiToken }}
  CDK_API_KEY: {{ .Values.console.apiToken | b64enc }}
  {{- end }}
  {{- if .Values.console.key }}
  CDK_KEY: {{ .Values.console.key | b64enc }}
  {{- end }}
{{- end }}
{{ if .Values.gateway.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "provisioner.gateway.config.secrets" . | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: conduktor-provisioning
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.gateway.password }}
  CDK_GATEWAY_PASSWORD: {{ .Values.gateway.password | b64enc }}
  {{- end }}
  {{- if .Values.gateway.key }}
  CDK_KEY: {{ .Values.gateway.key | b64enc }}
  {{- end }}
{{- end }}
